### DISCUSSION TITLE
Some fields doesn't have visual feedback for invalid state

### DISCUSSION THREAD

**Discussion by czernika** [orchidsoftware/platform#2645] [Ideas]
I have simple picture field

```php
Picture::make('picture')
     ->title('Picture')
    ->required(),
```

If validation fails (picture is required but I didn't upload any) visually I can not see where the error is
![Снимок экрана от 2023-06-16 20-47-40](https://github.com/orchidsoftware/platform/assets/86893348/7c78b392-0429-4708-8ad8-26c61989c576)

If I add some CSS like

```css
.was-validated [data-controller="picture"]:has(input:invalid) {
   border: 1px solid #dc3545;
}
```

Now I can see field is invalid

![Снимок экрана от 2023-06-16 20-48-50](https://github.com/orchidsoftware/platform/assets/86893348/b00721fb-3ccb-4eec-90d4-d34b05a865ee)

Same for some other fields

```css
.was-validated [data-controller="picture"]:has(input:invalid) {
   border: 1px solid #dc3545;
}

.was-validated [data-controller="cropper"]:has(input:invalid) {
   border: 1px solid #dc3545;
}

.was-validated [data-controller="quill"]:has(input:invalid) {
   border: 1px solid #dc3545;
}

.was-validated [data-controller="simplemde"]:has(textarea:invalid) {
   border: 1px solid #dc3545;
}
```

Although I didn't check properly every field for every possible validation rule (only `required`)

CSS `:has` is not [fully supported](https://caniuse.com/css-has) yet although it is better have at least some visual feedback than none. However it kinda depends on Bootstrap validation CSS (`.was-validated` class, error color) so I'm not sure about this specific implementation
