### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by Nks** [orchidsoftware/platform#1014]
Right now on the mobile tables looks very bad:
![image](https://user-images.githubusercontent.com/349293/68473862-1bbb3f80-0235-11ea-9db3-b1bcfb8031c8.png)

One other suggestion: add more responsive design to the tables. 

As example https://codepen.io/Jayesh_v/pen/xmModE

One other solution: have ability to fix one of the column and add horizontal scrolls to the tables.

**Comment by tabuna** [comment]
I think this is due to the fact that word wrap is enabled and the width is not set.

Perhaps it is worth putting a ban on the transfer and separately turning it on, for columns where it is needed?

**Comment by Hrache** [comment]
I've rotated records from horizontal to vertical 
![vertical-columns-orchid](https://user-images.githubusercontent.com/49149161/69563411-7c36d480-0fca-11ea-9c9f-2f95096a66f8.jpg)

**Comment by tabuna** [comment]
I think I'm ready to present a solution.
By default, all columns will be shown a ban on the transfer of words/letters. This prohibition will not be indicated for those whose width is not indicated.

How it will look:
![image](https://user-images.githubusercontent.com/5102591/77149823-8b72ee00-6aa3-11ea-9463-1d29ae282d6c.png)

![image](https://user-images.githubusercontent.com/5102591/77149888-a9405300-6aa3-11ea-9432-60799e817c2f.png)

![image](https://user-images.githubusercontent.com/5102591/77149916-b8270580-6aa3-11ea-9ad1-3b04b134fa94.png)

**Comment by tabuna** [comment]
**Release** 7.0.5 - 2020-03-20

**Comment by tabuna** [comment]
After the release, a lot of time has passed.
If you have problems feel free to rediscover it.

**Comment by d-damien** [comment]
Some CSS that may help. Makes everything in column.
```css
/* table responsive */
@media (max-width: 620px) {
    table.table tr {
        display: flex;
        flex-direction: column;
        border-bottom: 1px solid;
    }
    table.table tr td {
        width: inherit !important;
    }
    table.table tbody tr:nth-child(2n) {
        background-color: lavender;
    }
}
```
