### ISSUE TITLE
Changing Toast Position

### ISSUE THREAD

**Issue by alash3al** [orchidsoftware/platform#1161]
I'm using orchid in an RTL based app, and I want to change the Toast position to the left instead of the right, Is there a good way to do that?

**Comment by tabuna** [comment]
Hey. We do not have any explicit definition.
But you can do it with CSS. For example, add the following rule
```css
.toast-wrapper {
    left: 2em;
}
```
